Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users', include('users.urls')),
]

pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:p_id>/', views.pizza, name='pizza'),
    path('new_pizza/',views.new_pizza, name='new_pizza'),
    path('new_topping/<int:pizza_id>/',views.new_topping, name='new_topping'),
    path('edit_topping/<int:topping_id>/',views.edit_topping, name='edit_topping'),
    path('new_commment/<int:pizza_id>',views.new_comment, name='new_comment'),
]

users/urls.py
from django.urls import path, include

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return f"{self.topping[:50]}..." #name instead of topping

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "comments"

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms 
from . models import Pizza, Topping, Comment

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'name':''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['topping']
        labels = {'topping': ''}
        widgets = {'topping': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render,redirect
from .models import Pizza, Topping, Comment 
from .forms import PizzaForm, ToppingForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')

@login_required
def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')

    context = {'pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

@login_required
def pizza(request,p_id):
    pizza = Pizza.objects.get(id=p_id)



    toppings = pizza.topping_set.order_by('-date_added')
    
    context = {'pizza':pizza, 'toppings':toppings}

    return render(request, 'pizzas/pizza.html',context)

@login_required
def new_pizza(request):
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)

        if form.is_valid():
            form.save()

            return redirect('pizzas:pizzas')
    
    context = {'form': form}

    return render(request, 'pizzas/new_pizza.html', context)

@login_required
def new_topping(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    
    
    if request.method != 'POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data=request.POST)

        if form.is_valid():
            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.save()
            form.save()
            return redirect('pizzas:pizza', p_id=pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/new_topping.html', context)

@login_required
def edit_topping(request, topping_id):
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza

    if request.method != 'POST':
        form = ToppingForm(instance=topping)
    else:
        form = ToppingForm(instance=topping, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza', p_id=pizza.id)

    context = {'topping':topping, 'pizza':pizza, 'form':form}
    return render(request, 'pizzas/edit_topping.html', context)

        
def new_comment(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    
    
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            form.save()
            return redirect('pizzas:pizza', p_id=pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/new_comment.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Pizzeria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index'%}">
            Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav item">
                    <a class="nav-link" href="{% url 'pizzas:pizzas'%}">
                        Pizzas</a></li>
            </ul>
            <ul class="navbar-nav ml auto">
                {% if user.is_authenticated %}
                   <li class="nav-item">
                       <span class="navbar-text"}">Hello, {{user.username}}.</span>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                   </li>
                {% else%}
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

pizzas/templates/pizzas/edit_topping.html
{% extends "pizzas/base.html" %}

    {% block content %}
    
    <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

        <p>Edit topping:</p>

    <form action="{% url 'pizzas:edit_topping' topping.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Save Changes</button>
    </form>

    {% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">View pizzas here.</h1>

        <p class="lead">Make your own pizza, and add toppings to your pizzas.
            You can also view pizzas already made and write comments about them.</p>

        <a class="btn btn-lg btn-primary" href="{% url 'pizzas:pizzas' %}"
            role="button">Pizzas &raquo;</a>   
    </div>

    <p>
        <img src="https://www.greenwichpizzeria.com/images/slide-1.jpg"
        alt="Pizza">
    </p>
{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

    {% block content %}
    
    <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

        <p>Add a new comment:</p>

    <form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Add comment</button>
    </form>

    {% endblock content %}

pizzas/templates/pizzas/new_pizza.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Add a new pizza:</p>

<form action="{% url 'pizzas:new_pizza' %}" method='post'>
    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add pizza</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %}

    {% block content %}
    
    <p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

        <p>Add a new topping:</p>

    <form action="{% url 'pizzas:new_topping' pizza.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Add topping</button>
    </form>

    {% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}


{% block content%}
    <p>Pizza: {{ pizza.name }}</p>

    <ul>
        {% for topping in toppings %}

        <li>

            <p>{{ topping.name|linebreaks }}</p>

            <p>
                <a href="{% url 'pizzas:edit_topping' topping.id %}">Edit topping</a>
            </p>

        </li>
        {% empty %}
            <li>No toppings for this pizza have been added yet.</li>
        {% endfor %}

    </ul>

    <p>
        <a href="{% url 'pizzas:new_topping' pizza.id %}">Add a new topping</a>
    </p>

    <ul>
        {% for comment in comments %}

        <li>

            <p> {{ comment.name|linebreaks }}</p>

        </li>
        {% empty %}

            <li>No comments for this pizza have been added yet.</li>

        {% endfor %}

        </li>

    </ul>
    
    <p>
        <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>
    </p>
    
{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Pizzas</p>

<ul>

    {% for pizza in pizzas %}

    <li><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></li>
    {% empty %}
        <li> No pizzas have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'pizzas:new_pizza' %}">Add a new pizza</a>



{% endblock content %}